apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-a5vd
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/happy-path-with-depl-tenant/appstudio/dc-metro-map-a5vd@sha256:a5977bf365f07e42ee98d6172b3308129f95285e10c36f3d0bab674d3142d03a
        name: my-nodejs
        resources: {}
status: {}
